# Generated by Django 3.1.12 on 2025-01-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('country', models.CharField(default='US', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('payment_type', models.CharField(choices=[('CA', 'Cash'), ('CHECK', 'Check'), ('CREDIT CARD', 'Credit Card')], max_length=20)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('number_of_nights', models.IntegerField(default=1)),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('room_type', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField(default='11:00:00')),
                ('confirmation_code', models.CharField(max_length=50)),
                ('requested_room', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSubmission',
        ),
    ]
