# Generated by Django 3.1.12 on 2025-01-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0002_auto_20250127_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('nights', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('room_type', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='HotelReservation',
        ),
    ]
